### ISSUE TITLE
Add test via Test::Mojo

### ISSUE THREAD

**Issue by jberger** [yanick/Dancer2-Plugin-WebSocket#2]
In the course of writing an advent article (see it on the 20th, or look in the related link), I have been playing with testing Dancer apps with Test::Mojo. For a challenge, I wanted to see if it was possible to test a Dancer/WebSocket app with Test::Mojo and to my surprise it wasn't very hard (once I figured out how to start Twiggy as a library and get the ephemeral port out at startup).

I don't know how you'd want to actually stitch it in, but I offer you this shell of a test to help kick-start testing for this library, even if it would be optional tests when EV and Test::Mojo are installed. Let me know if and how you'd like it to work (namely how/where to load an app to test, the linked test uses the example app).

Cheers and happy holidays!

https://github.com/MojoliciousDotIO/mojolicious.io/blob/master/blog/2018/12/20/testing-dancer/websocket.t

**Comment by yanick** [comment]
I finally get to get around this. I can't tell you how tickled I am to have Dancer plugins made testable via Mojo tools. That's awesome!

I've pretty much ripped the example from the advent entry and shoved it as a test in the PR at #3.  Would you do us the honors to give it a look-over before I deploy it? :-)

**Comment by jberger** [comment]
I'm very glad you had this reaction. Tickles me. <3
